version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build: ./Tyres_management_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Tyres_management_project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./Front_end_react
    volumes:
      - ./Front_end_react:/frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://20.42.85.64:8000
