version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"  # Set authentication method to 'trust' for demo purposes

  web:
    build: ./Tyres_management_project  # Relative path to your Django project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Tyres_management_project:/app  # Relative path to your Django project
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # You may need to set database-related environment variables here, 
      # depending on your Django configuration
      # For example: DATABASE_URL="postgres://postgres@db:5432/yourdbname"

  frontend:
    build: ./Front_end_react  # Relative path to your React project
    volumes:
      - ./Front_end_react:/frontend  # Relative path to your React project
    ports:
      - "3000:3000"
