# Generated by Django 4.2.5 on 2023-09-16 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendsession',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weekendsession',
            name='race_weekend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Tyres_App.raceweekend'),
        ),
    ]
