# Generated by Django 4.2.5 on 2023-09-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0002_weekendsession_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreturn',
            name='tyre_type',
            field=models.CharField(choices=[('Soft', 'Soft'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TyreSetReturn',
        ),
    ]
