# Generated by Django 4.2.5 on 2023-09-17 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0004_weekendtemplate_remove_tyresetusage_tyre_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyreset',
            name='planned_return_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_return_tyres', to='Tyres_App.weekendsession'),
        ),
        migrations.AddField(
            model_name='tyreset',
            name='used_in_sessions',
            field=models.ManyToManyField(blank=True, related_name='used_tyres', to='Tyres_App.weekendsession'),
        ),
    ]
