# Generated by Django 4.2.5 on 2023-09-17 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0005_tyreset_planned_return_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreset',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_sets', to='Tyres_App.car'),
        ),
    ]
