# Generated by Django 4.2.5 on 2023-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0006_alter_tyreset_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekendtemplate',
            name='sessions',
        ),
        migrations.AddField(
            model_name='weekendtemplate',
            name='sessions',
            field=models.ManyToManyField(related_name='weekend_templates', to='Tyres_App.weekendsession'),
        ),
    ]
