# Generated by Django 4.2.5 on 2023-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0007_remove_weekendtemplate_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendtemplate',
            name='sessions',
            field=models.ManyToManyField(related_name='sessions', to='Tyres_App.weekendsession'),
        ),
    ]
