# Generated by Django 4.2.5 on 2023-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0008_alter_weekendtemplate_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendtemplate',
            name='sessions',
            field=models.ManyToManyField(related_name='weekend_templates', to='Tyres_App.weekendsession'),
        ),
    ]
