# Generated by Django 4.2.5 on 2023-09-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0009_alter_weekendtemplate_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendsession',
            name='weekend_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekend_sessions', to='Tyres_App.weekendformat'),
        ),
    ]
