# Generated by Django 4.2.5 on 2023-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0011_remove_weekendformat_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyreset',
            name='used_in_sessions',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_tyres', to='Tyres_App.weekendsession'),
        ),
    ]
