# Generated by Django 4.2.5 on 2023-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tyres_App', '0012_alter_tyreset_used_in_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendtemplate',
            name='sessions_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
